name: Generate Permanent Key and PEM
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v -keystore instafit.keystore -alias instafit_alias -keyalg RSA -keysize 2048 -validity 10000 -storepass instafit123 -keypass instafit123 -dname "CN=InstaFitCore, O=Dev, C=IN"
          
          # This command creates the .pem file Google needs for the reset
          keytool -export -rfc -keystore instafit.keystore -alias instafit_alias -file upload_certificate.pem -storepass instafit123
          
          # This creates the text for your GitHub Secret
          base64 -w 0 instafit.keystore > keystore_base64.txt

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: instafit-key-reset-files
          path: |
            instafit.keystore
            upload_certificate.pem
            keystore_base64.txt